
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    sudo apt update
    sudo apt -y install gfortran-9
  displayName: 'Installing gfortran-9'
- script: |
    mkdir build && cd build
    cmake .. -DCMAKE_Fortran_COMPILER=gfortran-9
    make -j
  displayName: 'Building gfortran-9-Release'
- script: |
    ls
    cd build
    make test
  displayName: 'Testing gfortran-9-Release'
- script: |
    cd build
    rm -r *
    cmake .. -DCMAKE_Fortran_COMPILER=gfortran-9 -DCMAKE_BUILD_TYPE=Debug
    make -j
  displayName: 'Building gfortran-9-Debug'
- script: |
    cd build
    make test
  displayName: 'Testing gfortran-9-Debug'
