trigger:
  - master

jobs:

- job: Debug
  pool:
    vmImage: 'Ubuntu-16.04'
  container: 
    image: chinoune/cl-gfortran-testing
  steps:
  - script: |
      mkdir build && cd build
      cmake .. -DCMAKE_BUILD_TYPE=Debug -DPFUNIT_DIR=/opt/pfunit/PFUNIT-4.0/cmake
      make -j$(nproc)
    displayName: 'Building gfortran-Debug'
  - script: |
      cd build
      make test
    displayName: 'Testing gfortran-Debug'


- job: Release
  pool:
    vmImage: 'Ubuntu-16.04'
  container: 
    image: chinoune/cl-gfortran-testing
  steps:
  - script: |
      mkdir build && cd build
      cmake .. -DPFUNIT_DIR=/opt/pfunit/PFUNIT-4.0/cmake
      make -j$(nproc)
    displayName: 'Building gfortran-Release'
  - script: |
      cd build
      make test
    displayName: 'Testing gfortran-Release'
