
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    sudo apt -y install gfortran-8
    mkdir build && cd build
    cmake ..
    make -j
    make test
  displayName: 'gcc-8-Release'
- script: |
    sudo apt -y install gfortran-8
    mkdir build && cd build
    cmake .. -DCMAKE_BUILD_TYPE=Debug
    make -j
    make test
  displayName: 'gcc-8-Debug'
