
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    sudo apt -y install gfortran-8
  displayName: 'Installing gfortran-8'
- script: |
    mkdir build && cd build
    cmake .. -DCMAKE_Fortran_COMPILER=gfortran-8
    make -j
  displayName: 'Building gfortran-8-Release'
- script: |
    make test
  displayName: 'Testing gfortran-8-Release'
- script: |
    rm -r *
    cmake .. -DCMAKE_Fortran_COMPILER=gfortran-8 -DCMAKE_BUILD_TYPE=Debug
    make -j
  displayName: 'Building gfortran-8-Debug'
- script: |
    make test
  displayName: 'Testing gfortran-8-Debug'
