
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

container: alpine:edge

steps:
- script: |
    apk update
    apk add openblas-dev cmake
  displayName: 'Installing required packages'
- script: |
    mkdir build && cd build
    cmake .. -DCMAKE_Fortran_COMPILER=gfortran
    make -j
  displayName: 'Building gfortran-Release'
- script: |
    ls
    cd build
    make test
  displayName: 'Testing gfortran-Release'
- script: |
    cd build
    rm -r *
    cmake .. -DCMAKE_Fortran_COMPILER=gfortran -DCMAKE_BUILD_TYPE=Debug
    make -j
  displayName: 'Building gfortran-Debug'
- script: |
    cd build
    make test
  displayName: 'Testing gfortran-Debug'
