
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    sudo apt -y install gfortran
    mkdir build && cd build
    cmake ..
    make -j
    make test
  displayName: 'gcc-6-Release'