
pipelines:
  default:
    - parallel:
      - step:
          name: old Debug
          image: chinoune/debian-gfortran-testing:old
          script:
           - mkdir build && cd build
           - cmake .. -DCMAKE_BUILD_TYPE=Debug -DPFUNIT_DIR=/opt/pfunit/PFUNIT-4.1/cmake
           - make -j$(nproc)
           - make test
      - step:
          name: old Release
          image: chinoune/debian-gfortran-testing:old
          script:
           - mkdir build && cd build
           - cmake .. -DPFUNIT_DIR=/opt/pfunit/PFUNIT-4.1/cmake
           - make -j$(nproc)
           - make test
      - step:
          name: stable Debug
          image: chinoune/debian-gfortran-testing:stable
          script:
           - mkdir build && cd build
           - cmake .. -DCMAKE_BUILD_TYPE=Debug -DPFUNIT_DIR=/opt/pfunit/PFUNIT-4.1/cmake
           - make -j$(nproc)
           - make test
      - step:
          name: stable Release
          image: chinoune/debian-gfortran-testing:stable
          script:
           - mkdir build && cd build
           - cmake .. -DPFUNIT_DIR=/opt/pfunit/PFUNIT-4.1/cmake
           - make -j$(nproc)
           - make test
      - step:
          name: trunk Debug
          image: chinoune/debian-gfortran-testing:trunk
          script:
           - mkdir build && cd build
           - cmake .. -DCMAKE_BUILD_TYPE=Debug -DPFUNIT_DIR=/opt/pfunit/PFUNIT-4.1/cmake
           - make -j$(nproc)
           - make test
      - step:
          name: trunk Release
          image: chinoune/debian-gfortran-testing:trunk
          script:
           - mkdir build && cd build
           - cmake .. -DPFUNIT_DIR=/opt/pfunit/PFUNIT-4.1/cmake
           - make -j$(nproc)
           - make test