image: chinoune/my-image

pipelines:
  default:
    - parallel:
      - step:
          name: Debug
          script:
           - mkdir build && cd build
           - cmake .. -DCMAKE_Fortran_COMPILER=gfortran -DCMAKE_BUILD_TYPE=Debug
           - make -j$(nproc)
           - make test
      - step:
          name: Release
          script:
           - mkdir build && cd build
           - cmake .. -DCMAKE_Fortran_COMPILER=gfortran -DCMAKE_BUILD_TYPE=Release
           - make -j$(nproc)
           - make test
      - step:
          name: gcc-trunk Debug
          image: zbeekman/nightly-gcc-trunk-docker-image
          script:
           - apt update
           - apt install -y cmake libopenblas-dev
           - mkdir build && cd build
           - cmake .. -DCMAKE_Fortran_COMPILER=gfortran -DCMAKE_BUILD_TYPE=Debug
           - make -j$(nproc)
           - make test
      - step:
          name: gcc-trunk Release
          image: zbeekman/nightly-gcc-trunk-docker-image
          script:
           - apt update
           - apt install -y cmake libopenblas-dev
           - mkdir build && cd build
           - cmake .. -DCMAKE_Fortran_COMPILER=gfortran -DCMAKE_BUILD_TYPE=Release
           - make -j$(nproc)
           - make test